DROP SCHEMA IF EXISTS seip_audit CASCADE;
DROP SCHEMA IF EXISTS seip_staging CASCADE;
DROP SCHEMA IF EXISTS seip_core CASCADE;
DROP EXTENSION IF EXISTS pg_trgm;
DROP EXTENSION IF EXISTS postgis;
DROP EXTENSION IF EXISTS "uuid-ossp";
